name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode sumber
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependensi
        run: npm install

      # - name: Lakukan migrasi database
      #   run: npm run migrate
      #   env:
      #     NODE_ENV: development  # Set NODE_ENV ke "production" untuk mode produksi

      - name: Jalankan Aplikasi
        run: npm run dev
